```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#namespace
library(RODBC)
library(tidyverse)
```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Query All ED Patients
dsn <- "VhaCdwDwhSql33.vha.med.va.gov"
con <- odbcConnect(dsn, uid = "",  pwd = "")
queryEDAll <- c("
SELECT DISTINCT
  CAST(EDIS.PatientArrivalDateTime AS date) AS ArrivalDate,
  SPat.PatientSSN,
  SPat.PatientLastName,
  SPat.PatientFirstName
FROM
  LSV.EDIS.EDISLog AS EDIS
  INNER JOIN LSV.Dim.Location As Loc
    ON EDIS.LocationSID = Loc.LocationSID
  LEFT JOIN LSV.SPatient.SPatient AS SPat
    ON EDIS.PatientSID = SPat.PatientSID
WHERE 
  EDIS.Sta3n = '612'
  AND EDIS.PatientArrivalDateTime >= DATEADD(DAY, -30, GETDATE())
  AND SPat.TestPatientFlag IS NULL
  AND Loc.LocationSID = '132765'
")
backup_EDAll <- sqlQuery(con, queryEDAll)
odbcCloseAll()
rm('con', 'dsn', 'queryEDAll')
```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Query Health Factors 'Sepsis Result NO'
dsn <- "VhaCdwDwhSql33.vha.med.va.gov"
con <- odbcConnect(dsn, uid = "",  pwd = "")
queryHFacNo <- c("
SELECT DISTINCT
  CAST(EDIS.PatientArrivalDateTime AS date) AS ArrivalDate,
  SPat.PatientSSN,
  SPat.PatientLastName,
  SPat.PatientFirstName
FROM
  LSV.EDIS.EDISLog AS EDIS
  INNER JOIN LSV.Dim.Location As Loc
    ON EDIS.LocationSID = Loc.LocationSID
  INNER JOIN LSV.SPatient.SPatient AS SPat
    ON EDIS.Sta3n = SPat.Sta3n
    AND EDIS.PatientSID = SPat.PatientSID
  INNER JOIN LSV.HF.HealthFactor AS HFac
    ON EDIS.Sta3n = HFac.Sta3n
    AND EDIS.PatientSID = HFac.PatientSID
    AND EDIS.VisitSID = HFac.VisitSID
  INNER JOIN LSV.Dim.HealthFactorType AS DimHFac
    ON HFac.Sta3n = DimHFac.Sta3n
    AND HFac.HealthFactorTypeSID = DimHFac.HealthFactorTypeSID
WHERE 
  EDIS.Sta3n = '612'
  AND EDIS.PatientArrivalDateTime >= DATEADD(DAY, -30, GETDATE())
  AND SPat.TestPatientFlag IS NULL
  AND DimHFac.HealthFactorType = 'ED SEPSIS NO CRITERIA'
  AND EDIS.LocationSID ='132765'
")
backup_HFacNo <- sqlQuery(con, queryHFacNo)
odbcCloseAll()
rm('con', 'dsn', 'queryHFacNo')
```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Query Health Factors 'Sepsis Result YES'
dsn <- "VhaCdwDwhSql33.vha.med.va.gov"
con <- odbcConnect(dsn, uid = "",  pwd = "")
queryHFacYes <- c("
SELECT DISTINCT
  CAST(EDIS.PatientArrivalDateTime AS date) AS ArrivalDate,
  SPat.PatientSSN,
  SPat.PatientLastName,
  SPat.PatientFirstName
FROM
  LSV.EDIS.EDISLog AS EDIS
  INNER JOIN LSV.Dim.Location As Loc
    ON EDIS.LocationSID = Loc.LocationSID
  INNER JOIN LSV.SPatient.SPatient AS SPat
    ON EDIS.Sta3n = SPat.Sta3n
    AND EDIS.PatientSID = SPat.PatientSID
  INNER JOIN LSV.HF.HealthFactor AS HFac
    ON EDIS.Sta3n = HFac.Sta3n
    AND EDIS.PatientSID = HFac.PatientSID
    AND EDIS.VisitSID = HFac.VisitSID
  INNER JOIN LSV.Dim.HealthFactorType AS DimHFac
    ON HFac.Sta3n = DimHFac.Sta3n
    AND HFac.HealthFactorTypeSID = DimHFac.HealthFactorTypeSID
WHERE 
  EDIS.Sta3n = '612'
  AND EDIS.PatientArrivalDateTime >= DATEADD(DAY, -30, GETDATE())
  AND SPat.TestPatientFlag IS NULL
  AND DimHFac.HealthFactorType = 'ED SEPSIS YES CRITERIA' 
  AND EDIS.LocationSID ='132765'
")
backup_HFacYes <- sqlQuery(con, queryHFacYes)
odbcCloseAll()
rm('con', 'dsn', 'queryHFacYes')
```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Query Vitals
dsn <- "VhaCdwDwhSql33.vha.med.va.gov"
con <- odbcConnect(dsn, uid = "",  pwd = "")
queryVitals <- c("
SELECT
  PatientSSN,
  PatientLastName,
  PatientFirstName,
  --ArrivalDate,
  VitalsDateTime,
  VitalsDate,
  VitalsTime,
  VitalType,
  Systolic,
  Result
FROM
  (
  SELECT DISTINCT
    SPat.PatientSSN AS PatientSSN,
    SPat.PatientLastName AS PatientLastName,
    SPat.PatientFirstName AS PatientFirstName,
    CAST(EDIS.PatientArrivalDateTime AS date) AS ArrivalDate,
    Vitals.VitalSignEnteredDateTime AS VitalsDateTime,
    CAST(Vitals.VitalSignEnteredDateTime AS date) AS VitalsDate,
    FORMAT(Vitals.VitalSignEnteredDateTime, 'hh:mm') AS VitalsTime,
    DimVType.VitalType AS VitalType,
    Vitals.Systolic AS Systolic,
    Vitals.VitalResult AS Result
  FROM
    LSV.EDIS.EDISLog AS EDIS
    INNER JOIN LSV.Dim.Location As Loc
      ON EDIS.LocationSID = Loc.LocationSID
    INNER JOIN LSV.SPatient.SPatient AS SPat
      ON EDIS.Sta3n = SPat.Sta3n
      AND EDIS.PatientSID = SPat.PatientSID
    INNER JOIN LSV.Vital.VitalSign AS Vitals
      ON EDIS.Sta3n = Vitals.Sta3n
      AND EDIS.PatientSID = Vitals.PatientSID
    INNER JOIN LSV.Dim.VitalType AS DimVType
      ON Vitals.Sta3n = DimVType.Sta3n
      AND Vitals.VitalTypeSID = DimVType.VitalTypeSID
  WHERE
    EDIS.Sta3n = '612'
    AND EDIS.PatientArrivalDateTime >= DATEADD(DAY, -30, GETDATE())
    AND SPat.TestPatientFlag IS NULL
    AND Loc.LocationSID = '132765'
    AND Vitals.VitalSignEnteredDateTime BETWEEN EDIS.PatientArrivalDateTime AND   DATEADD(hour, +1, EDIS.PatientArrivalDateTime)
    AND DimVType.VitalType IN ('PULSE', 'TEMPERATURE', 'RESPIRATION', 'BLOOD PRESSURE')
  GROUP BY
    SPat.PatientSSN,SPat.PatientLastName,SPat.PatientFirstName,EDIS.PatientArrivalDateTime,Vitals.VitalSignEnteredDateTime,Vitals.VitalSignEnteredDateTime,DimVType.VitalType,Vitals.Systolic,Vitals.VitalResult
  ) AS InnerQ
WHERE
  ArrivalDate = VitalsDate
GROUP BY
  PatientSSN, PatientLastName, PatientFirstName, VitalsDateTime, VitalsDate, VitalsTime, VitalType, Systolic, Result
ORDER BY
  PatientSSN, PatientLastName, PatientFirstName, VitalsDateTime, VitalType, Systolic, Result
")
backup_Vitals <- sqlQuery(con, queryVitals)
odbcCloseAll()
rm('con', 'dsn', 'queryVitals')
```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Query Labs
dsn <- "VhaCdwDwhSql33.vha.med.va.gov"
con <- odbcConnect(dsn, uid = "",  pwd = "")
queryLabs <- c("
SELECT DISTINCT
  CAST(EDIS.PatientArrivalDateTime AS DATE) AS LabsArrivalDate,
  SPat.PatientSSN AS LabsPatientSSN,
  CAST(Labs.LabChemSpecimenDateTime AS DATE) AS LabsDate,
  Labs.LabChemSpecimenDateTime AS LabsTime,
  Labs.LabChemResultValue AS NEUT
FROM
  LSV.EDIS.EDISLog AS EDIS
  INNER JOIN LSV.Dim.Location As Loc
    ON EDIS.LocationSID = Loc.LocationSID
  INNER JOIN LSV.SPatient.SPatient AS SPat
    ON EDIS.Sta3n = SPat.Sta3n
    AND EDIS.PatientSID = SPat.PatientSID
  LEFT JOIN LSV.Chem.PatientLabChem AS Labs
    ON Labs.Sta3n = SPat.Sta3n
    AND Labs.PatientSID = SPat.PatientSID
  INNER JOIN LSV.Dim.LabChemTest AS DimLabs
    ON DimLabs.Sta3n = Labs.Sta3n
    AND DimLabs.LabChemTestSID = Labs.LabChemTestSID
WHERE
  EDIS.Sta3n = '612'
  AND EDIS.PatientArrivalDateTime >= DATEADD(DAY, -30, GETDATE())
  AND SPat.TestPatientFlag IS NULL
  AND Loc.LocationSID = '132765'
  AND CAST(EDIS.PatientArrivalDateTime AS DATE) = CAST(Labs.LabChemSpecimenDateTime AS DATE)
  AND DimLabs.LabChemPrintTestName = 'NEUT #'
")
backup_Labs <- sqlQuery(con, queryLabs)
odbcCloseAll()
rm('con', 'dsn', 'queryLabs')
```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Data manipulations (on separate sets)

#EDAll
EDAll <- as_tibble(backup_EDAll)
#Get counts by date
countAll <- EDAll %>% select(ArrivalDate) %>% group_by(ArrivalDate) %>% summarise("all" = n())

#HFacNo
HFacNo <- as_tibble(backup_HFacNo)
#Set flag
HFacNo$HFacNoFlag <- as.numeric(1)
#Get counts by date
countNo <- HFacNo %>% select(ArrivalDate) %>% group_by(ArrivalDate) %>% summarise("no" = n())

#HFacYes
HFacYes <- as_tibble(backup_HFacYes)
#Set flag
HFacYes$HFacYesFlag <- as.numeric(1)
#Get counts by date
countYes <- HFacYes %>% select(ArrivalDate) %>% group_by(ArrivalDate) %>% summarise("yes" = n()) 


#Vitals
Vitals <- (backup_Vitals)
Vitals$value <- as.character(Vitals$Result) %>% sapply(function(x) {if (!grepl("/",as.character(x))) x else strsplit(x,'/')[[1]][1]}) %>% as.numeric()
Vitals$VitalsTime <- Vitals$VitalsDateTime  %>% sapply(function(x) strftime(x,'%Y-%m-%d %H:%M:%S'))
Vitals <- select(Vitals, -Systolic, -Result)
#uq_patientssn <-  c("027607951" ,"104267685" )

vital_type = c("BLOOD PRESSURE", "PULSE","RESPIRATION","TEMPERATURE")

get_date_set <- function(date) {
  date_set <- Vitals %>% filter(PatientSSN == uq_patientssn, VitalsDate == date)
  vital_idx <- sapply(vital_type, function(x) which(date_set$VitalType == x)[1]) %>% as.vector()
  flag = (sapply(date_set[vital_idx,]$VitalType, function(x) is.na(x)) %>% sum())
  return (list(date_set = date_set[vital_idx,],missing_flag = flag, date = date, sirs_flag = filterFlag(date_set[vital_idx,])))
}
l = list()

for (uq_patientssn in unique(Vitals$PatientSSN)[70:77]) {
  print(uq_patientssn)
  uq_patient <- Vitals %>% filter(PatientSSN == uq_patientssn)
  uq_dates <- unique(uq_patient$VitalsDate)
    
  for (i in 1:length(uq_dates)) {
    date <- uq_dates[i]
    date_list = list()
    date <- (as.Date(date, origin = "1970-01-01"))
    print(date)
    l[[uq_patientssn]][[i]] <- (get_date_set(date))
  }
}

filterFlag <- function(x) {
  flag_count = 0
  spread_it <- x[,c(7,8)] %>% spread(key = VitalType, value = value)
  v_types <- names(spread_it)
  for (v in v_types) {
    if (v == 'PULSE') {
      if (spread_it[['PULSE']] > 90.0) {
        flag_count =  flag_count + 1
      }
    }
    if (v == 'TEMPERATURE') {
      if (spread_it['TEMPERATURE'] > 100.0  | spread_it['TEMPERATURE'] < 95.0) {
        flag_count = flag_count + 1 
      }
    }
    if (v == 'BLOOD PRESSURE') {
      if ( spread_it['BLOOD PRESSURE'] < 90.0) {
        flag_count = flag_count + 1
      }
    }
    if (v == 'RESPIRATION') {
      if (spread_it['RESPIRATION'] > 20) {
        flag_count = flag_count + 1
      }
    }
  }
  return(flag_count)
}

neut_flag <- function(x) {
  if (x >= 12 | x <= 4) {
    flag = 1
  } else { 
    flag = 0
  }
  print(x)
  return(flag)
}


#Labs
labs <-(backup_Labs) #%>% group_by(LabsPatientSSN) %>% summarise(lt = min(LabsTime))
labs$NEUT <-labs$NEUT %>% as.numeric()
uq_patientssn <- unique(labs$LabsPatientSSN)
uq_patientssn = '010247235'
uq_dates <-labs[labs$LabsPatientSSN == uq_patientssn,] %>% as.data.frame()
early_set <- uq_dates  %>% group_by(LabsDate) %>% summarise(LabsTime = min(LabsTime))

a<-uq_dates %>% inner_join(early_set, c('LabsDate','LabsTime'))
a$NEUT <- as.numeric(a$NEUT)
a$flag_neut <- sapply(as.numeric(a$NEUT), function(x)  (x >=12 | x<=4 ) )






L <- labs %>% select(-LabsArrivalDate)
lab_list <- list()
labSubList <- list()
uniqs <- L$LabsPatientSSN %>% unique() %>% levels()
for (i in 1:length(uniqs[1:20])) {
  labSubList['LabsPatientSSN'] <- uniqs[i]
  uq <- L %>% filter(LabsPatientSSN == uniqs[i])
  uq$NEUT <- as.character(uq$NEUT)
  uqDate <- uq$LabsDate %>% unique()
    for (date in uqDate) {
      dateList = list()
      dateList[['Date']] <- as.Date(date, origin = "1970-01-01")
      data <- uq[(uq$LabsPatientSSN == uniqs[i] & uq$LabsDate == date),]
      values = list()
      for (x in 1:dim(data)[1]) {
        values[[data[x,]$NEUT]] = data$NEUT[x]
      }
    }
  lab_list[[i]] <- uq$NEUT
}
for (i in 1:length(lab_list)) {
  line <- rbind(line, lab_list[[i]])
}
for (i in 1:length(lab_list)) {
  lab_list[[i]] <- lab_list[[i]][1]
}




#Combine datasets
EDIS_SIRS <- tibble()

EDIS_SIRS <- left_join(select(EDAll, -ArrivalDate), select(HFacNo, -PatientLastName, -PatientFirstName), "PatientSSN") 

EDIS_SIRS <- left_join(EDIS_SIRS, select(HFacYes, -PatientLastName, -PatientFirstName), "PatientSSN")


#Data manipulations (on combined sets)







#Set flags
Vitals$BPFlag <- as.numeric(Vitals$`BLOOD PRESSURE` <= 90)
Vitals$PulseFlag <- as.numeric(Vitals$PULSE >= 90)
Vitals$RespFlag <- as.numeric(Vitals$RESPIRATION >= 30)
Vitals$TempFlag <- as.numeric((Vitals$TEMPERATURE >= 100.4  | Vitals$TEMPERATURE <= 96.8))
Vitals$sirsFlag <- as.numeric(Vitals[,c(11:14)] %>% apply(1, sum) > 0)

```

```{r, echo=FALSE,results='hide',fig.keep='all', warning=FALSE, message=FALSE}
#Plotz
ggplot(data = countsByDate, fill = all) +
  geom_bar(aes(x = ArrivalDate, y = yes), position = "dodge", stat = "identity") +
  labs(x = "Arrival date", y = "Sepsis criteria satisfied (count)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(date_breaks = "day", date_labels = "%b-%d")

ggplot(data = countsByDate) +
  geom_bar(aes(x = ArrivalDate, y = ratio), stat = "identity") +
  labs(x = "Arrival date", y = "Sepsis criteria satisfied (ratio)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(date_breaks = "day", date_labels = "%b-%d")

ggplot(data = countsByDate, aes(x = yes)) +
  geom_histogram(fill = "#FF45A0", binwidth = .5)
  
  
```